export const CHUNK_SIZE = 16;
export const RENDER_DISTANCE = 8;
export const RENDER_DISTANCE_Y = 3; // vertical chunk render distance
export const CHUNKS_PER_FRAME = 4; // max chunks to generate per frame
export const BLOCK_SIZE = 1;
export const GRAVITY = 25;
export const JUMP_SPEED = 9;
export const PLAYER_SPEED = 5;
export const PLAYER_HEIGHT = 1.8;
export const PLAYER_WIDTH = 0.6;
export const MOUSE_SENSITIVITY = 0.002;
export const CROUCH_HEIGHT = 1.5;
export const CROUCH_SPEED_MULT = 0.3;
