export const CHUNK_SIZE = 16;
export const RENDER_DISTANCE = 8;
export const RENDER_DISTANCE_Y = 3;
export const UNLOAD_HYSTERESIS = 2; // buffer beyond render distance before unloading
export const CHUNKS_PER_FRAME = 1;
export const MESH_UPLOADS_PER_FRAME = 2;
export const BLOCK_SIZE = 1;
export const GRAVITY = 32; // 0.08 blocks/tick² at 20 ticks/s
export const JUMP_SPEED = 9;
export const PLAYER_SPEED = 5;
export const PLAYER_HEIGHT = 1.8;
export const PLAYER_WIDTH = 0.6;
export const MOUSE_SENSITIVITY = 0.002;
export const CROUCH_HEIGHT = 1.5;
export const CROUCH_SPEED_MULT = 0.3;
export const SPRINT_SPEED_MULT = 1.3;
export const DOUBLE_TAP_WINDOW = 300;
export const DEFAULT_FOV = 75;
export const SPRINT_FOV = 85;
